import "package:flutter/material.dart";

class MaterialTheme {
  static ColorScheme blueLight() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff2800ae),
      surfaceTint: Color(0xff4f33ff),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff3a01ed),
      onPrimaryContainer: Color(0xffe9e4ff),
      secondary: Color(0xff302684),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff6861bf),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff600069),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff850092),
      onTertiaryContainer: Color(0xffffdefa),
      error: Color(0xff740006),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffcf2c27),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffcf8ff),
      onSurface: Color(0xff11101a),
      onSurfaceVariant: Color(0xff363446),
      outline: Color(0xff525063),
      outlineVariant: Color(0xff6d6b7e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff302f3b),
      inversePrimary: Color(0xffc5c0ff),
      primaryFixed: Color(0xff614eff),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff4522f6),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff6861bf),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff4f48a4),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xffae38b8),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff91179d),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc8c4d3),
      surfaceBright: Color(0xfffcf8ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff6f2ff),
      surfaceContainer: Color(0xffeae6f6),
      surfaceContainerHigh: Color(0xffdfdbea),
      surfaceContainerHighest: Color(0xffd3cfdf),
    );
  }

  static ColorScheme blueDark() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffddd8ff),
      surfaceTint: Color(0xffc5c0ff),
      onPrimary: Color(0xff1c0084),
      primaryContainer: Color(0xff8a80ff),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffddd8ff),
      onSecondary: Color(0xff1e1074),
      secondaryContainer: Color(0xff8c85e6),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffffcdfb),
      onTertiary: Color(0xff47004e),
      tertiaryContainer: Color(0xffd760df),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffd2cc),
      onError: Color(0xff540003),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff13121d),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffdedaf0),
      outline: Color(0xffb3afc5),
      outlineVariant: Color(0xff918ea2),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe4e0f0),
      inversePrimary: Color(0xff3700e4),
      primaryFixed: Color(0xffe3dfff),
      onPrimaryFixed: Color(0xff0b004a),
      primaryFixedDim: Color(0xffc5c0ff),
      onPrimaryFixedVariant: Color(0xff2900b2),
      secondaryFixed: Color(0xffe3dfff),
      onSecondaryFixed: Color(0xff0b004a),
      secondaryFixedDim: Color(0xffc5c0ff),
      onSecondaryFixedVariant: Color(0xff302684),
      tertiaryFixed: Color(0xffffd6fa),
      onTertiaryFixed: Color(0xff25002a),
      tertiaryFixedDim: Color(0xffffa9ff),
      onTertiaryFixedVariant: Color(0xff62006c),
      surfaceDim: Color(0xff13121d),
      surfaceBright: Color(0xff45434f),
      surfaceContainerLowest: Color(0xff070610),
      surfaceContainerLow: Color(0xff1d1c27),
      surfaceContainer: Color(0xff282732),
      surfaceContainerHigh: Color(0xff33313d),
      surfaceContainerHighest: Color(0xff3e3c48),
    );
  }

  static ColorScheme greenLight() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff233d00),
      surfaceTint: Color(0xff3f6900),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff4a7a00),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff233d00),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff56772e),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff003f27),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff007d52),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff740006),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffcf2c27),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfff7fbe9),
      onSurface: Color(0xff0e1309),
      onSurfaceVariant: Color(0xff313927),
      outline: Color(0xff4d5542),
      outlineVariant: Color(0xff68705b),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff2d3226),
      inversePrimary: Color(0xff92da38),
      primaryFixed: Color(0xff4a7a00),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff385f00),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff56772e),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff3e5d17),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff007d52),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff00623f),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc4c8b8),
      surfaceBright: Color(0xfff7fbe9),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff1f6e4),
      surfaceContainer: Color(0xffe6ead9),
      surfaceContainerHigh: Color(0xffdadfcd),
      surfaceContainerHighest: Color(0xffcfd4c3),
    );
  }

  static ColorScheme greenDark() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffa7f14d),
      surfaceTint: Color(0xff92da38),
      onPrimary: Color(0xff172b00),
      primaryContainer: Color(0xff74b90f),
      onPrimaryContainer: Color(0xff102000),
      secondary: Color(0xffc2e992),
      onSecondary: Color(0xff172b00),
      secondaryContainer: Color(0xff789b4e),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xff61f6b2),
      onTertiary: Color(0xff002c1a),
      tertiaryContainer: Color(0xff00be7f),
      onTertiaryContainer: Color(0xff002113),
      error: Color(0xffffd2cc),
      onError: Color(0xff540003),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff10150b),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffd7e0c6),
      outline: Color(0xffadb59d),
      outlineVariant: Color(0xff8b937d),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe0e4d3),
      inversePrimary: Color(0xff2f5100),
      primaryFixed: Color(0xffadf753),
      onPrimaryFixed: Color(0xff081400),
      primaryFixedDim: Color(0xff92da38),
      onPrimaryFixedVariant: Color(0xff233d00),
      secondaryFixed: Color(0xffc8ef98),
      onSecondaryFixed: Color(0xff081400),
      secondaryFixedDim: Color(0xffacd37e),
      onSecondaryFixedVariant: Color(0xff233d00),
      tertiaryFixed: Color(0xff68fcb7),
      onTertiaryFixed: Color(0xff00150a),
      tertiaryFixedDim: Color(0xff46df9d),
      onTertiaryFixedVariant: Color(0xff003f27),
      surfaceDim: Color(0xff10150b),
      surfaceBright: Color(0xff414639),
      surfaceContainerLowest: Color(0xff050802),
      surfaceContainerLow: Color(0xff1a1f14),
      surfaceContainer: Color(0xff25291e),
      surfaceContainerHigh: Color(0xff2f3428),
      surfaceContainerHighest: Color(0xff3a3f33),
    );
  }

  static ColorScheme greyLight() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff383727),
      surfaceTint: Color(0xff605f4d),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff6f6e5b),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff37362f),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff6f6d64),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff2f382f),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff667065),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff740006),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffcf2c27),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffdf9f5),
      onSurface: Color(0xff121110),
      onSurfaceVariant: Color(0xff37362e),
      outline: Color(0xff54534a),
      outlineVariant: Color(0xff6f6d64),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff31302e),
      inversePrimary: Color(0xffcac7b1),
      primaryFixed: Color(0xff6f6e5b),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff575544),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff6f6d64),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff56554d),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff667065),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff4e574d),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc9c6c3),
      surfaceBright: Color(0xfffdf9f5),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff7f3f0),
      surfaceContainer: Color(0xffebe7e4),
      surfaceContainerHigh: Color(0xffe0dcd9),
      surfaceContainerHighest: Color(0xffd4d1ce),
    );
  }

  static ColorScheme greyDark() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffefebd4),
      surfaceTint: Color(0xffcac7b1),
      onPrimary: Color(0xff313021),
      primaryContainer: Color(0xffd2cfb9),
      onPrimaryContainer: Color(0xff3d3c2c),
      secondary: Color(0xffe0dcd1),
      onSecondary: Color(0xff27261f),
      secondaryContainer: Color(0xff939187),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffe3ede0),
      onTertiary: Color(0xff293129),
      tertiaryContainer: Color(0xffc7d1c4),
      onTertiaryContainer: Color(0xff353e34),
      error: Color(0xffffd2cc),
      onError: Color(0xff540003),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff141312),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffe0dcd1),
      outline: Color(0xffb5b2a7),
      outlineVariant: Color(0xff939086),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe6e2df),
      inversePrimary: Color(0xff4a4938),
      primaryFixed: Color(0xffe6e3cd),
      onPrimaryFixed: Color(0xff121205),
      primaryFixedDim: Color(0xffcac7b1),
      onPrimaryFixedVariant: Color(0xff383727),
      secondaryFixed: Color(0xffe6e2d7),
      onSecondaryFixed: Color(0xff12110b),
      secondaryFixedDim: Color(0xffcac6bc),
      onSecondaryFixedVariant: Color(0xff37362f),
      tertiaryFixed: Color(0xffdbe5d8),
      onTertiaryFixed: Color(0xff0b130c),
      tertiaryFixedDim: Color(0xffbfc9bc),
      onTertiaryFixedVariant: Color(0xff2f382f),
      surfaceDim: Color(0xff141312),
      surfaceBright: Color(0xff454442),
      surfaceContainerLowest: Color(0xff080706),
      surfaceContainerLow: Color(0xff1e1d1c),
      surfaceContainer: Color(0xff292826),
      surfaceContainerHigh: Color(0xff333231),
      surfaceContainerHighest: Color(0xff3f3d3c),
    );
  }

  static ColorScheme purpleLight() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff42003b),
      surfaceTint: Color(0xff943c85),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff630c59),
      onPrimaryContainer: Color(0xfffff1f7),
      secondary: Color(0xff43203b),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff633c5a),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff490013),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff6c0e24),
      onTertiaryContainer: Color(0xfffff2f1),
      error: Color(0xff600004),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff98000a),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffff7f9),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff000000),
      outline: Color(0xff352831),
      outlineVariant: Color(0xff54454f),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff362e33),
      inversePrimary: Color(0xfffface9),
      primaryFixed: Color(0xff7b256e),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff5f0756),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff633c5a),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff4a2642),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff872436),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff680a21),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc3b5bc),
      surfaceBright: Color(0xfffff7f9),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffcedf4),
      surfaceContainer: Color(0xffeddfe6),
      surfaceContainerHigh: Color(0xffdfd1d7),
      surfaceContainerHighest: Color(0xffd1c3ca),
    );
  }

  static ColorScheme purpleDark() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffeaf5),
      surfaceTint: Color(0xfffface9),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffffa6e9),
      onPrimaryContainer: Color(0xff1d001a),
      secondary: Color(0xffffeaf5),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffe6b4d7),
      onSecondaryContainer: Color(0xff1c0118),
      tertiary: Color(0xffffebec),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffffacb4),
      onTertiaryContainer: Color(0xff210005),
      error: Color(0xffffece9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffaea4),
      onErrorContainer: Color(0xff220001),
      surface: Color(0xff181116),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffffffff),
      outline: Color(0xffffeaf5),
      outlineVariant: Color(0xffd1bdc9),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffeddfe6),
      inversePrimary: Color(0xff79246d),
      primaryFixed: Color(0xffffd7f1),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xfffface9),
      onPrimaryFixedVariant: Color(0xff280023),
      secondaryFixed: Color(0xffffd7f1),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffeab7db),
      onSecondaryFixedVariant: Color(0xff23051f),
      tertiaryFixed: Color(0xffffdadb),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffffb2b9),
      onTertiaryFixedVariant: Color(0xff2c0008),
      surfaceDim: Color(0xff181116),
      surfaceBright: Color(0xff574d53),
      surfaceContainerLowest: Color(0xff000000),
      surfaceContainerLow: Color(0xff251d22),
      surfaceContainer: Color(0xff362e33),
      surfaceContainerHigh: Color(0xff42393e),
      surfaceContainerHighest: Color(0xff4e444a),
    );
  }

  static ColorScheme yellowLight() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff373900),
      surfaceTint: Color(0xff5f620d),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff6e711d),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff373817),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff6e6f49),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff113f0b),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff49783e),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff740006),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffcf2c27),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffdf9ee),
      onSurface: Color(0xff11110b),
      onSurfaceVariant: Color(0xff373729),
      outline: Color(0xff545344),
      outlineVariant: Color(0xff6e6e5e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313129),
      inversePrimary: Color(0xffc9cc6e),
      primaryFixed: Color(0xff6e711d),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff565801),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff6e6f49),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff565733),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff49783e),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff325f28),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc9c6bc),
      surfaceBright: Color(0xfffdf9ee),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff7f4e8),
      surfaceContainer: Color(0xffebe8dd),
      surfaceContainerHigh: Color(0xffe0ddd2),
      surfaceContainerHighest: Color(0xffd4d2c7),
    );
  }

  static ColorScheme yellowDark() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xfffdffaa),
      surfaceTint: Color(0xffc9cc6e),
      onPrimary: Color(0xff313300),
      primaryContainer: Color(0xffe0e382),
      onPrimaryContainer: Color(0xff464800),
      secondary: Color(0xffdfdfb1),
      onSecondary: Color(0xff262708),
      secondaryContainer: Color(0xff93936a),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffedffe1),
      onTertiary: Color(0xff0a3905),
      tertiaryContainer: Color(0xffb6eba4),
      onTertiaryContainer: Color(0xff214e19),
      error: Color(0xffffd2cc),
      onError: Color(0xff540003),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff14140d),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffdfddc9),
      outline: Color(0xffb4b3a0),
      outlineVariant: Color(0xff929180),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2d8),
      inversePrimary: Color(0xff494b00),
      primaryFixed: Color(0xffe5e887),
      onPrimaryFixed: Color(0xff111200),
      primaryFixedDim: Color(0xffc9cc6e),
      onPrimaryFixedVariant: Color(0xff373900),
      secondaryFixed: Color(0xffe5e5b7),
      onSecondaryFixed: Color(0xff111200),
      secondaryFixedDim: Color(0xffc9c99c),
      onSecondaryFixedVariant: Color(0xff373817),
      tertiaryFixed: Color(0xffbcf1a9),
      onTertiaryFixed: Color(0xff001600),
      tertiaryFixedDim: Color(0xffa0d48f),
      onTertiaryFixedVariant: Color(0xff113f0b),
      surfaceDim: Color(0xff14140d),
      surfaceBright: Color(0xff45453d),
      surfaceContainerLowest: Color(0xff080804),
      surfaceContainerLow: Color(0xff1e1e17),
      surfaceContainer: Color(0xff282821),
      surfaceContainerHigh: Color(0xff33332c),
      surfaceContainerHighest: Color(0xff3f3e36),
    );
  }

  List<ExtendedColor> get extendedColors => [];
}

class ExtendedColor {
  final Color seed, value;
  final ColorFamily light;
  final ColorFamily lightHighContrast;
  final ColorFamily lightMediumContrast;
  final ColorFamily dark;
  final ColorFamily darkHighContrast;
  final ColorFamily darkMediumContrast;

  const ExtendedColor({
    required this.seed,
    required this.value,
    required this.light,
    required this.lightHighContrast,
    required this.lightMediumContrast,
    required this.dark,
    required this.darkHighContrast,
    required this.darkMediumContrast,
  });
}

class ColorFamily {
  const ColorFamily({
    required this.color,
    required this.onColor,
    required this.colorContainer,
    required this.onColorContainer,
  });

  final Color color;
  final Color onColor;
  final Color colorContainer;
  final Color onColorContainer;
}
